version: '3.7'
services:
  blank-app:
    build:
      context: .
      dockerfile: ./docker/blank-app/Dockerfile
    volumes:
      - .:/app:rw
    restart: always
  forward:
    build:
      context: .
      dockerfile: ./docker/forward/Dockerfile
    volumes:
      - ./d1/forward.py:/app/d1/forward.py:ro
      - ./tmp/cache/forward_data:/app/tmp/cache/forward_data:ro
    restart: always
