version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./d1/nginx_config.py:/app/d1/nginx_config.py:ro
      - ./tmp/cache/forward.nginx.json:/app/tmp/cache/forward.nginx.json:ro
    restart: always
  dynu:
    build:
      context: .
      dockerfile: ./docker/dynu/Dockerfile
    volumes:
      - ./d1/dynu_update.py:/app/d1/dynu_update.py:ro
      - ./tmp/cache/dynu.auth.json:/app/tmp/cache/dynu.auth.json:ro
    restart: always
    links:
      - ngrok
  ngrok:
    image: wernight/ngrok
    links:
      - app
    command: ['ngrok', 'http', 'app:80']
    volumes:
      - ./tmp/cache/ngrok.yml:/home/ngrok/.ngrok2/ngrok.yml:ro
    restart: always
  #forward:
  #  build:
  #    context: .
  #    dockerfile: ./docker/forward/Dockerfile
  #  volumes:
  #    - ./d1/forward.py:/app/d1/forward.py:ro
  #    - ./tmp/cache/forward_data:/app/tmp/cache/forward_data:ro
  #  restart: always
