name: ipython_docs
channels:
 - conda-forge
 - defaults
dependencies:
  - python=3.8
  - setuptools>=18.5
  - sphinx>=4.2
  - sphinx_rtd_theme>=1.0
  - numpy
  - nose
  - testpath
  - matplotlib
  - pip:
    - docrepr
    - prompt_toolkit
    - ipykernel
    - stack_data
